version: "3.7"

services:
  numbers-api:
    healthcheck:
      test: ["CMD", "dotnet", "Utilities.HttpCheck.dll", "-u", "http://localhost/health", "-t", "500"]
      interval: 2s
      retries: 2
      start_period: 5s
      timeout: 3s
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.50"
          memory: 75M
      update_config:
        parallelism: 3
        monitor: 60s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 6
        order: start-first
        failure_action: continue

  numbers-web:
    ports:
      - mode: host
        published: 80
        target: 80
    healthcheck:
      interval: 20s
      retries: 3
      start_period: 30s
      timeout: 10s
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.75"
          memory: 150M

networks:
  app-net:
    name: numbers-prod